### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by GevorgAntonyan** [jacob-shuman/node-itunes-search#10] opened 2020-07-03 09:17 UTC
Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at phin (/var/www/node-main/node_modules/node-itunes-search/build/search/search.js:16:33)
    at IncomingMessage.<anonymous> (/var/www/node-main/node_modules/phin/lib/phin.compiled.js:1:2162)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
undefined

**Comment by jacob-shuman** [comment] 2020-10-01 06:40
I can't seem to reproduce this, do you recall the structure of the request?

**Comment by micahjon** [comment] 2022-03-15 07:06
Today I ran into another case where this happened, not b/c of an invalid URL but simply due to a bad response from the iTunes API:

```html
<html><head><title>Error</title></head><body>Your request produced an error.  <BR>[newNullResponse]</body></html>
```

Trying the request again worked fine. It appears that once in a great while the iTunes API doesn't work, which is to be expected from any real-world API I suppose. It could be a rate limiting feature (happened when I was making a bunch of requests to autocomplete some search results), but I'm not sure.

Regardless, I submitted a PR that handles invalid JSON from the iTunes API. By decoding the response with `phar` instead of manually, the Promise is rejected instead of a fatal error being thrown that aborts the Node process. In my case, it's the difference between my `Fastify` server's Node process being shut down and it being able to continue to handle requests.
https://github.com/jacob-shuman/node-itunes-search/pull/18

**Comment by micahjon** [comment] 2022-03-15 07:08
Just for reference, here's the exact error I ran into:

```
undefined:1
<html><head><title>Error</title></head><body>Your request produced an error.  <BR>[newNullResponse]</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/micah/Sites/micahs-project/backend/node_modules/node-itunes-search/build/search/search.js:16:33
    at IncomingMessage.<anonymous> (/Users/micah/Sites/micahs-project/backend/node_modules/phin/lib/phin.compiled.js:1:2100)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by micahjon** [comment] 2022-03-18 06:12
Hey @jacob-shuman, thanks for merging #18 . Looks like we just need a new npm release and then we can close this issue.

**Comment by jacob-shuman** [comment] 2022-03-18 18:35
Just published the new release :smile:! I really appreciate the help @micahjon!

**Closed by jacob-shuman** 2022-03-18 18:35 UTC
Labels: bug
